# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='game',
        ),
        migrations.RemoveField(
            model_name='link',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cts_app.Platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
