# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0002_auto_20160210_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
    ]
