# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0002_auto_20170419_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(null=True, verbose_name='release date'),
        ),
    ]
