# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0003_auto_20170420_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='link',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cts_app.Game'),
        ),
        migrations.AddField(
            model_name='link',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cts_app.Platform'),
        ),
    ]
