# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0003_remove_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_name',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 16, 5, 0, 354720, tzinfo=utc), max_length=1000, verbose_name='Link Name'),
            preserve_default=False,
        ),
    ]
