# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0004_link_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cts_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(verbose_name='Added')),
                ('nickname', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=2000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cts_app.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cts_app.Platform')),
            ],
        ),
    ]
