# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0006_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cts_app.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='req',
            name='mic',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
