# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0006_auto_20160215_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='apply time',
        ),
        migrations.AddField(
            model_name='req',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 10, 26, 8, 514803, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
