# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0007_auto_20170503_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
    ]
