# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0008_remove_game_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('game', 'platform')]),
        ),
    ]
