# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0008_auto_20160222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='comment',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='req',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
