# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0011_votes_pub_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=set([('user', 'voted_user')]),
        ),
    ]
