# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_app', '0012_auto_20160324_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
